#!/usr/bin/env bash

_capfc_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "--capf --host --timeout --certificate --password --help" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _capfc_completion capfc

_capfctl_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "--list --set --delete --export --operation --keysize --password --help" -- "$2"))
    elif [[ $3 = --operation ]]; then
        COMPREPLY=($(compgen -W "install fetch delete none" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _capfctl_completion capfctl

_capfd_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "--capf --issuer --port --timeout --days --help" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _capfd_completion capfd

_tvsc_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "--tvs --host --timeout --device --help" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _tvsc_completion tvsc

_tvsctl_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "--insert --list --delete --export --sast --ccm --tftp \
                                 --ccm-tftp --capf --app-server --tvs --ttl --help" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _tvsctl_completion tvsctl

_tvsd_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "--tvs --port --timeout --ttl --help" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _tvsd_completion tvsd
