#!/bin/bash

_capfc_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "-A --capf -h --host -t --timeout -c --certificate -p --password -H --help" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _capfc_completion capfc

_capfctl_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "-l --list -s --set -d --delete -e --export \
                                 -o --operation -S --keysize -p --password -H --help" -- "$2"))
    elif [[ $3 = -o || $3 == --operation ]]; then
        COMPREPLY=($(compgen -W "install fetch delete none" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _capfctl_completion capfctl

_capfd_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "-A --capf -i --issuer -p --port -t --timeout -d --days -H --help" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _capfd_completion capfd

_tvsc_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "-T --tvs -h --host -t --timeout -d --device -H --help" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _tvsc_completion tvsc

_tvsctl_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "-i --insert -l --list -d --delete -e --export -s --sast -c -ccm -t --tftp \
                                 -C --ccm-tftp -A --capf -a --app-server -T --tvs -L --ttl -H --help" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _tvsctl_completion tvsctl

_tvsd_completion() {
    if [[ ${2:0:1} = - ]]; then
        COMPREPLY=($(compgen -W "-T --tvs -p --port -t --timeout -L --ttl -H --help" -- "$2"))
    else
        COMPREPLY=($(compgen -f -- "$2"))
    fi

    return 0
}

complete -F _tvsd_completion tvsd
