#!/usr/bin/python3
#
# Copyright (c) 2021 Gareth Palmer <gareth.palmer3@gmail.com>
# This program is free software, distributed under the terms of
# the GNU General Public License Version 2.

import sys
import os
import os.path
import getopt
import traceback
import binascii
import sqlite3

from cryptography import x509
from cryptography.hazmat import backends
from cryptography.hazmat.primitives import hashes, serialization


ROLE_SAST = 0
ROLE_CCM = 1
ROLE_CCM_TFTP = 2
ROLE_TFTP = 3
ROLE_CAPF = 4
ROLE_APP_SERVER = 7
ROLE_TVS = 21


class ProgramError(Exception):
    pass


def initalise_database(database):
    cursor = database.cursor()

    cursor.execute('CREATE TABLE certificates (id INTEGER PRIMARY KEY, certificate_hash TEXT UNIQUE NOT NULL, '
                   'serial_number TEXT NOT NULL, subject_name TEXT NOT NULL, issuer_name TEXT NOT NULL, '
                   'certificate TEXT NOT NULL, roles TEXT NOT NULL, ttl INTEGER)')

    database.commit()


role_names = {
    'SAST': ROLE_SAST,
    'CCM': ROLE_CCM,
    'CCM+TFTP': ROLE_CCM_TFTP,
    'TFTP': ROLE_TFTP,
    'CAPF': ROLE_CAPF,
    'APP-SERVER': ROLE_APP_SERVER,
    'TVS': ROLE_TVS
}


def insert_certificate(database, certificate_file, roles, ttl):
    try:
        with open(certificate_file, 'rb') as file:
            certificate = file.read()

    except (PermissionError, FileNotFoundError, IsADirectoryError) as error:
        raise ProgramError(f'{error.strerror}: {error.filename}')

    try:
        certificate = x509.load_pem_x509_certificate(certificate, backends.default_backend())
    except ValueError:
        raise ProgramError(f'No certificate in file: {certificate_file}')

    serial_number = serial_number = certificate.serial_number
    serial_number = serial_number.to_bytes((serial_number.bit_length() + 7) // 8, byteorder = 'big')
    serial_number = binascii.hexlify(serial_number).decode('utf-8')

    subject_name = ''

    for attribute in certificate.subject:
        subject_name += (';' if len(subject_name) else '') + attribute.rfc4514_string()

    issuer_name = ''

    for attribute in certificate.issuer:
        issuer_name += (';' if len(issuer_name) else '') + attribute.rfc4514_string()

    certificate_hash = certificate.fingerprint(hashes.SHA256())
    certificate_hash = binascii.hexlify(certificate_hash).decode('utf-8')

    roles = ','.join(sorted(roles, key = lambda role: role_names[role]))
    cursor = database.cursor()

    cursor.execute('INSERT INTO certificates (certificate_hash, serial_number, subject_name, issuer_name, certificate, roles, ttl) '
                   'VALUES (?, ?, ?, ?, ?, ?, ?) '
                   'ON CONFLICT (certificate_hash) DO UPDATE SET roles = excluded.roles, ttl = excluded.ttl',
                   (certificate_hash,
                    serial_number,
                    subject_name,
                    issuer_name,
                    certificate.public_bytes(serialization.Encoding.PEM),
                    roles,
                    ttl))

    database.commit()

    print('Inserted', subject_name, 'with', roles)


def delete_certificate(database, id):
    cursor = database.cursor()

    # RETURNING clause only available in sqlite >= 3.35
    cursor.execute('SELECT subject_name, roles FROM certificates WHERE id = ?',
                   (id,))

    row = cursor.fetchone()

    if row is None:
        print(f'No certificate with ID: {id}')
        return

    cursor.execute('DELETE FROM certificates WHERE id = ?',
                   (id,))

    database.commit()

    print('Deleted',  row['subject_name'], 'with', row['roles'])


def export_certificate(database, id):
    cursor = database.cursor()

    cursor.execute('SELECT certificate FROM certificates WHERE id = ?',
                   (id,))

    row = cursor.fetchone()

    if row is None:
        print(f'No certificate with ID: {id}')
        return

    print(row['certificate'].decode('utf-8'), end = '')


def list_certificates(database):
    cursor = database.cursor()

    cursor.execute('SELECT id, certificate_hash, serial_number, subject_name, issuer_name, roles, ttl '
                   'FROM certificates ORDER BY id ASC')

    rows = cursor.fetchall()

    if not len(rows):
        print('No certificates in database')
        return

    for row in rows:
        print('ID:              ', row['id'])
        print('Serial Number:   ', row['serial_number'])
        print('Subject Name:    ', row['subject_name'])
        print('Issuer Name:     ', row['issuer_name'])

        for role in row['roles'].split(','):
            print('Role:            ', role)

        if row['ttl']:
            print('TTL:             ', row['ttl'])

        print('Certificate Hash:', row['certificate_hash'])
        print('')


def main():
    try:
        short_options = 'i:d:e:lL:scCtAaTH'
        long_options = ['insert=', 'delete=', 'export=', 'list', 'ttl=', 'sast', 'ccm', 'ccm-tftp', 'tftp', 'capf', 'app-server', 'tvs', 'help']

        try:
            options, arguments = getopt.gnu_getopt(sys.argv[1:], short_options, long_options)
        except getopt.GetoptError as error:
            raise ProgramError(error.msg[0].upper() + error.msg[1:])

        mode = None
        database_file = None
        certificate_file = None
        roles = set()
        ttl = None
        help = False

        for option, argument in options:
            if option in ('-i', '--insert'):
                mode = 'insert'
                certificate_file = argument

            elif option in ('-d', '--delete'):
                mode = 'delete'
                id = argument

                try:
                    id = int(id)
                except ValueError:
                    raise ProgramError(f'Invalid ID: {id}')

            elif option in ('-e', '--export'):
                mode = 'export'
                id = argument

                try:
                    id = int(id)
                except ValueError:
                    raise ProgramError(f'Invalid ID: {id}')

            elif option in ('-l', '--list'):
                mode = 'list'

            elif option in ('-L', '--ttl'):
                ttl = argument

                try:
                    ttl = int(ttl)
                except ValueError:
                    raise ProgramError(f'Invalid ttl: {ttl}')

                if ttl < 1 or ttl > 2592000:
                    raise ProgramError(f'TTL must be between 1 and 2592000')

            elif option in ('-s', '--sast'):
                roles.add('SAST')

            elif option in ('-c', '--ccm'):
                roles.add('CCM')

            elif option in ('-C', '--ccm-tftp'):
                roles.add('CCM+TFTP')

            elif option in ('-t', '--tftp'):
                roles.add('TFTP')

            elif option in ('-A', '--capf'):
                roles.add('CAPF')

            elif option in ('-a', '--app-server'):
                roles.add('APP-SERVER')

            elif option in ('-T', '--tvs'):
                roles.add('TVS')

            elif option in ('-H', '--help'):
                help = True

        if help:
            print('Usage: ' + os.path.basename(sys.argv[0]) + ' [OPTIONS] DATABASE-FILE\n'
                  'Manage the certificate database for TVS.\n'
                  '\n'
                  '  -i, --insert CERT-FILE          insert/replace certificate and roles into database\n'
                  '  -s, --sast                      insert certificate with the SAST role\n'
                  '  -c, --ccm                       insert certificate with CCM role\n'
                  '  -t, --tftp                      insert certificate with TFTP role\n'
                  '  -C, --ccm-tftp                  insert certificate with CCM+TFTP role\n'
                  '  -A, --capf                      insert certificate with CAPF role\n'
                  '  -a, --app-server                insert certificate with APP-SERVER role\n'
                  '  -T, --tvs                       insert certificate with TVS role\n'
                  '  -L, --ttl LIFETIME              response validity lifetime\n'
                  '  -l, --list                      list certificates\n'
                  '  -d, --delete ID                 delete certificate from database\n'
                  '  -e, --export ID                 export certificate from database\n'
                  '  -H, --help                      print this help and exit\n'
                  '\n'
                  'DATABASE-FILE will be automatically created if it does not exist.\n'
                  'Inserting a certificate that already exists will overwrite that entry.\n')

            return

        if mode is None:
            raise ProgramError('No mode specified (insert, delete, export or list). Try --help')

        if not len(arguments):
            raise ProgramError('No database file specified')

        database_file = arguments[0]

        with sqlite3.connect(database_file) as database:
            # Empty database
            if not os.path.getsize(database_file):
                initalise_database(database)

            database.row_factory = sqlite3.Row

            if mode == 'insert':
                if not len(roles):
                    raise ProgramError('No roles specified')

                insert_certificate(database, certificate_file, roles, ttl)

            elif mode == 'delete':
                delete_certificate(database, id)

            elif mode == 'export':
                export_certificate(database, id)

            elif mode == 'list':
                list_certificates(database)

    except ProgramError as error:
        print(str(error), file = sys.stderr)
        exit(1)

    except Exception:
        traceback.print_exc(file = sys.stderr)
        exit(1)

    exit(0)


if __name__ == '__main__':
    main()
