name: python lint
  
on:
  push:
    branches:
      - master
    paths:
      - 'tvsc'
      - 'tvsd'
      - 'tlsctl'
      - 'capfc'
      - 'capfd'
      - 'capfctl'
      - '.pylintrc'
      - '.github/workflows/pylint.yml'

  pull_request:
    branches:
      - master
    paths:
      - 'tvsc'
      - 'tvsd'
      - 'tlsctl'
      - 'capfc'
      - 'capfd'
      - 'capfctl'
      - '.pylintrc'
      - '.github/workflows/pylint.yml'

  workflow_dispatch:

jobs:
  lint:
    name: Run python linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install packages
        run: |
          sudo apt install pylint python3-cryptography

      - name: Run pylint 
        run: |
          pylint tvsd tvsc tvsctl capfd capfc capfctl
